FROM ubuntu:jammy-20220531
RUN apt update
RUN DEBIAN_FRONTEND=noninteractive apt install -y cmake git g++ doxygen graphviz bash rsync curl libblas-dev liblapack-dev libeigen3-dev liblapacke-dev ninja-build
RUN DEBIAN_FRONTEND=noninteractive apt install -y python

